// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: currency.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetBalanceRequest 残高取得リクエスト
type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetBalanceResponse 残高取得レスポンス
type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balances      map[string]string      `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // "paid" => "1000", "free" => "500" (整数値の文字列)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceResponse) GetBalances() map[string]string {
	if x != nil {
		return x.Balances
	}
	return nil
}

// GrantRequest 通貨付与リクエスト
type GrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyType  string                 `protobuf:"bytes,2,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"` // "paid" or "free"
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`                                 // 整数値の文字列（例: "100"）
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Requester     string                 `protobuf:"bytes,6,opt,name=requester,proto3" json:"requester,omitempty"` // リクエスト元（サービス名やユーザーIDなど）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRequest) Reset() {
	*x = GrantRequest{}
	mi := &file_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRequest) ProtoMessage() {}

func (x *GrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRequest.ProtoReflect.Descriptor instead.
func (*GrantRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{2}
}

func (x *GrantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GrantRequest) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *GrantRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GrantRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GrantRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GrantRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

// GrantResponse 通貨付与レスポンス
type GrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	BalanceAfter  string                 `protobuf:"bytes,2,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"` // 整数値の文字列（例: "600"）
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantResponse) Reset() {
	*x = GrantResponse{}
	mi := &file_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantResponse) ProtoMessage() {}

func (x *GrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantResponse.ProtoReflect.Descriptor instead.
func (*GrantResponse) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{3}
}

func (x *GrantResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GrantResponse) GetBalanceAfter() string {
	if x != nil {
		return x.BalanceAfter
	}
	return ""
}

func (x *GrantResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ConsumeRequest 通貨消費リクエスト
type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyType  string                 `protobuf:"bytes,2,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"` // "paid", "free", or "auto"
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`                                 // 整数値の文字列（例: "50"）
	ItemId        string                 `protobuf:"bytes,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	UsePriority   bool                   `protobuf:"varint,5,opt,name=use_priority,json=usePriority,proto3" json:"use_priority,omitempty"` // 優先順位制御（無料通貨優先）
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Requester     string                 `protobuf:"bytes,7,opt,name=requester,proto3" json:"requester,omitempty"` // リクエスト元（サービス名やユーザーIDなど）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{4}
}

func (x *ConsumeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConsumeRequest) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *ConsumeRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ConsumeRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ConsumeRequest) GetUsePriority() bool {
	if x != nil {
		return x.UsePriority
	}
	return false
}

func (x *ConsumeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ConsumeRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

// ConsumeResponse 通貨消費レスポンス
type ConsumeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransactionId      string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ConsumptionDetails []*ConsumptionDetail   `protobuf:"bytes,2,rep,name=consumption_details,json=consumptionDetails,proto3" json:"consumption_details,omitempty"` // 優先順位制御使用時
	BalanceAfter       string                 `protobuf:"bytes,3,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`                   // 単一通貨タイプ消費時
	TotalConsumed      string                 `protobuf:"bytes,4,opt,name=total_consumed,json=totalConsumed,proto3" json:"total_consumed,omitempty"`                // 優先順位制御使用時
	Status             string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_currency_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumeResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ConsumeResponse) GetConsumptionDetails() []*ConsumptionDetail {
	if x != nil {
		return x.ConsumptionDetails
	}
	return nil
}

func (x *ConsumeResponse) GetBalanceAfter() string {
	if x != nil {
		return x.BalanceAfter
	}
	return ""
}

func (x *ConsumeResponse) GetTotalConsumed() string {
	if x != nil {
		return x.TotalConsumed
	}
	return ""
}

func (x *ConsumeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ConsumptionDetail 消費詳細
type ConsumptionDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyType  string                 `protobuf:"bytes,1,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`    // "paid" or "free"
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`                                    // 整数値の文字列
	BalanceBefore string                 `protobuf:"bytes,3,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"` // 整数値の文字列
	BalanceAfter  string                 `protobuf:"bytes,4,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`    // 整数値の文字列
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumptionDetail) Reset() {
	*x = ConsumptionDetail{}
	mi := &file_currency_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionDetail) ProtoMessage() {}

func (x *ConsumptionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionDetail.ProtoReflect.Descriptor instead.
func (*ConsumptionDetail) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{6}
}

func (x *ConsumptionDetail) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *ConsumptionDetail) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ConsumptionDetail) GetBalanceBefore() string {
	if x != nil {
		return x.BalanceBefore
	}
	return ""
}

func (x *ConsumptionDetail) GetBalanceAfter() string {
	if x != nil {
		return x.BalanceAfter
	}
	return ""
}

// ProcessPaymentRequest 決済処理リクエスト
type ProcessPaymentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentRequestId string                 `protobuf:"bytes,1,opt,name=payment_request_id,json=paymentRequestId,proto3" json:"payment_request_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MethodName       string                 `protobuf:"bytes,3,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Details          map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Amount           string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency         string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_currency_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessPaymentRequest) GetPaymentRequestId() string {
	if x != nil {
		return x.PaymentRequestId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *ProcessPaymentRequest) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ProcessPaymentRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ProcessPaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// ProcessPaymentResponse 決済処理レスポンス
type ProcessPaymentResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransactionId      string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PaymentRequestId   string                 `protobuf:"bytes,2,opt,name=payment_request_id,json=paymentRequestId,proto3" json:"payment_request_id,omitempty"`
	ConsumptionDetails []*ConsumptionDetail   `protobuf:"bytes,3,rep,name=consumption_details,json=consumptionDetails,proto3" json:"consumption_details,omitempty"`
	TotalConsumed      string                 `protobuf:"bytes,4,opt,name=total_consumed,json=totalConsumed,proto3" json:"total_consumed,omitempty"`
	Status             string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_currency_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessPaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ProcessPaymentResponse) GetPaymentRequestId() string {
	if x != nil {
		return x.PaymentRequestId
	}
	return ""
}

func (x *ProcessPaymentResponse) GetConsumptionDetails() []*ConsumptionDetail {
	if x != nil {
		return x.ConsumptionDetails
	}
	return nil
}

func (x *ProcessPaymentResponse) GetTotalConsumed() string {
	if x != nil {
		return x.TotalConsumed
	}
	return ""
}

func (x *ProcessPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// RedeemCodeRequest コード引き換えリクエスト
type RedeemCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemCodeRequest) Reset() {
	*x = RedeemCodeRequest{}
	mi := &file_currency_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemCodeRequest) ProtoMessage() {}

func (x *RedeemCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemCodeRequest.ProtoReflect.Descriptor instead.
func (*RedeemCodeRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{9}
}

func (x *RedeemCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RedeemCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// RedeemCodeResponse コード引き換えレスポンス
type RedeemCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedemptionId  string                 `protobuf:"bytes,1,opt,name=redemption_id,json=redemptionId,proto3" json:"redemption_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CurrencyType  string                 `protobuf:"bytes,4,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	BalanceAfter  string                 `protobuf:"bytes,6,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemCodeResponse) Reset() {
	*x = RedeemCodeResponse{}
	mi := &file_currency_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemCodeResponse) ProtoMessage() {}

func (x *RedeemCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemCodeResponse.ProtoReflect.Descriptor instead.
func (*RedeemCodeResponse) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{10}
}

func (x *RedeemCodeResponse) GetRedemptionId() string {
	if x != nil {
		return x.RedemptionId
	}
	return ""
}

func (x *RedeemCodeResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RedeemCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RedeemCodeResponse) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *RedeemCodeResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *RedeemCodeResponse) GetBalanceAfter() string {
	if x != nil {
		return x.BalanceAfter
	}
	return ""
}

func (x *RedeemCodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetTransactionHistoryRequest トランザクション履歴取得リクエスト
type GetTransactionHistoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	CurrencyType    string                 `protobuf:"bytes,4,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`          // optional
	TransactionType string                 `protobuf:"bytes,5,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // optional
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTransactionHistoryRequest) Reset() {
	*x = GetTransactionHistoryRequest{}
	mi := &file_currency_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryRequest) ProtoMessage() {}

func (x *GetTransactionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{11}
}

func (x *GetTransactionHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTransactionHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransactionHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetTransactionHistoryRequest) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *GetTransactionHistoryRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

// GetTransactionHistoryResponse トランザクション履歴取得レスポンス
type GetTransactionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryResponse) Reset() {
	*x = GetTransactionHistoryResponse{}
	mi := &file_currency_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryResponse) ProtoMessage() {}

func (x *GetTransactionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{12}
}

func (x *GetTransactionHistoryResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTransactionHistoryResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransactionHistoryResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Transaction トランザクション
type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TransactionType string                 `protobuf:"bytes,2,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	CurrencyType    string                 `protobuf:"bytes,3,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
	Amount          string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`                                    // 整数値の文字列（例: "100"）
	BalanceBefore   string                 `protobuf:"bytes,5,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"` // 整数値の文字列（例: "500"）
	BalanceAfter    string                 `protobuf:"bytes,6,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`    // 整数値の文字列（例: "600"）
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_currency_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{13}
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *Transaction) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetBalanceBefore() string {
	if x != nil {
		return x.BalanceBefore
	}
	return ""
}

func (x *Transaction) GetBalanceAfter() string {
	if x != nil {
		return x.BalanceAfter
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_currency_proto protoreflect.FileDescriptor

const file_currency_proto_rawDesc = "" +
	"\n" +
	"\x0ecurrency.proto\x12\bcurrency\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb2\x01\n" +
	"\x12GetBalanceResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12F\n" +
	"\bbalances\x18\x02 \x03(\v2*.currency.GetBalanceResponse.BalancesEntryR\bbalances\x1a;\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x02\n" +
	"\fGrantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rcurrency_type\x18\x02 \x01(\tR\fcurrencyType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12@\n" +
	"\bmetadata\x18\x05 \x03(\v2$.currency.GrantRequest.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\trequester\x18\x06 \x01(\tR\trequester\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\rGrantResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12#\n" +
	"\rbalance_after\x18\x02 \x01(\tR\fbalanceAfter\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xc1\x02\n" +
	"\x0eConsumeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rcurrency_type\x18\x02 \x01(\tR\fcurrencyType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\tR\x06itemId\x12!\n" +
	"\fuse_priority\x18\x05 \x01(\bR\vusePriority\x12B\n" +
	"\bmetadata\x18\x06 \x03(\v2&.currency.ConsumeRequest.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\trequester\x18\a \x01(\tR\trequester\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xea\x01\n" +
	"\x0fConsumeResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12L\n" +
	"\x13consumption_details\x18\x02 \x03(\v2\x1b.currency.ConsumptionDetailR\x12consumptionDetails\x12#\n" +
	"\rbalance_after\x18\x03 \x01(\tR\fbalanceAfter\x12%\n" +
	"\x0etotal_consumed\x18\x04 \x01(\tR\rtotalConsumed\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x9c\x01\n" +
	"\x11ConsumptionDetail\x12#\n" +
	"\rcurrency_type\x18\x01 \x01(\tR\fcurrencyType\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12%\n" +
	"\x0ebalance_before\x18\x03 \x01(\tR\rbalanceBefore\x12#\n" +
	"\rbalance_after\x18\x04 \x01(\tR\fbalanceAfter\"\xb7\x02\n" +
	"\x15ProcessPaymentRequest\x12,\n" +
	"\x12payment_request_id\x18\x01 \x01(\tR\x10paymentRequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmethod_name\x18\x03 \x01(\tR\n" +
	"methodName\x12F\n" +
	"\adetails\x18\x04 \x03(\v2,.currency.ProcessPaymentRequest.DetailsEntryR\adetails\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x01\n" +
	"\x16ProcessPaymentResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12,\n" +
	"\x12payment_request_id\x18\x02 \x01(\tR\x10paymentRequestId\x12L\n" +
	"\x13consumption_details\x18\x03 \x03(\v2\x1b.currency.ConsumptionDetailR\x12consumptionDetails\x12%\n" +
	"\x0etotal_consumed\x18\x04 \x01(\tR\rtotalConsumed\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"@\n" +
	"\x11RedeemCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xee\x01\n" +
	"\x12RedeemCodeResponse\x12#\n" +
	"\rredemption_id\x18\x01 \x01(\tR\fredemptionId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12#\n" +
	"\rcurrency_type\x18\x04 \x01(\tR\fcurrencyType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12#\n" +
	"\rbalance_after\x18\x06 \x01(\tR\fbalanceAfter\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xb5\x01\n" +
	"\x1cGetTransactionHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12#\n" +
	"\rcurrency_type\x18\x04 \x01(\tR\fcurrencyType\x12)\n" +
	"\x10transaction_type\x18\x05 \x01(\tR\x0ftransactionType\"\x9e\x01\n" +
	"\x1dGetTransactionHistoryResponse\x129\n" +
	"\ftransactions\x18\x01 \x03(\v2\x15.currency.TransactionR\ftransactions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x9f\x02\n" +
	"\vTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12)\n" +
	"\x10transaction_type\x18\x02 \x01(\tR\x0ftransactionType\x12#\n" +
	"\rcurrency_type\x18\x03 \x01(\tR\fcurrencyType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12%\n" +
	"\x0ebalance_before\x18\x05 \x01(\tR\rbalanceBefore\x12#\n" +
	"\rbalance_after\x18\x06 \x01(\tR\fbalanceAfter\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt2\xdc\x03\n" +
	"\x0fCurrencyService\x12G\n" +
	"\n" +
	"GetBalance\x12\x1b.currency.GetBalanceRequest\x1a\x1c.currency.GetBalanceResponse\x128\n" +
	"\x05Grant\x12\x16.currency.GrantRequest\x1a\x17.currency.GrantResponse\x12>\n" +
	"\aConsume\x12\x18.currency.ConsumeRequest\x1a\x19.currency.ConsumeResponse\x12S\n" +
	"\x0eProcessPayment\x12\x1f.currency.ProcessPaymentRequest\x1a .currency.ProcessPaymentResponse\x12G\n" +
	"\n" +
	"RedeemCode\x12\x1b.currency.RedeemCodeRequest\x1a\x1c.currency.RedeemCodeResponse\x12h\n" +
	"\x15GetTransactionHistory\x12&.currency.GetTransactionHistoryRequest\x1a'.currency.GetTransactionHistoryResponseB-Z+gem-server/internal/presentation/grpc/pb;pbb\x06proto3"

var (
	file_currency_proto_rawDescOnce sync.Once
	file_currency_proto_rawDescData []byte
)

func file_currency_proto_rawDescGZIP() []byte {
	file_currency_proto_rawDescOnce.Do(func() {
		file_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_currency_proto_rawDesc), len(file_currency_proto_rawDesc)))
	})
	return file_currency_proto_rawDescData
}

var file_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_currency_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),             // 0: currency.GetBalanceRequest
	(*GetBalanceResponse)(nil),            // 1: currency.GetBalanceResponse
	(*GrantRequest)(nil),                  // 2: currency.GrantRequest
	(*GrantResponse)(nil),                 // 3: currency.GrantResponse
	(*ConsumeRequest)(nil),                // 4: currency.ConsumeRequest
	(*ConsumeResponse)(nil),               // 5: currency.ConsumeResponse
	(*ConsumptionDetail)(nil),             // 6: currency.ConsumptionDetail
	(*ProcessPaymentRequest)(nil),         // 7: currency.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil),        // 8: currency.ProcessPaymentResponse
	(*RedeemCodeRequest)(nil),             // 9: currency.RedeemCodeRequest
	(*RedeemCodeResponse)(nil),            // 10: currency.RedeemCodeResponse
	(*GetTransactionHistoryRequest)(nil),  // 11: currency.GetTransactionHistoryRequest
	(*GetTransactionHistoryResponse)(nil), // 12: currency.GetTransactionHistoryResponse
	(*Transaction)(nil),                   // 13: currency.Transaction
	nil,                                   // 14: currency.GetBalanceResponse.BalancesEntry
	nil,                                   // 15: currency.GrantRequest.MetadataEntry
	nil,                                   // 16: currency.ConsumeRequest.MetadataEntry
	nil,                                   // 17: currency.ProcessPaymentRequest.DetailsEntry
}
var file_currency_proto_depIdxs = []int32{
	14, // 0: currency.GetBalanceResponse.balances:type_name -> currency.GetBalanceResponse.BalancesEntry
	15, // 1: currency.GrantRequest.metadata:type_name -> currency.GrantRequest.MetadataEntry
	16, // 2: currency.ConsumeRequest.metadata:type_name -> currency.ConsumeRequest.MetadataEntry
	6,  // 3: currency.ConsumeResponse.consumption_details:type_name -> currency.ConsumptionDetail
	17, // 4: currency.ProcessPaymentRequest.details:type_name -> currency.ProcessPaymentRequest.DetailsEntry
	6,  // 5: currency.ProcessPaymentResponse.consumption_details:type_name -> currency.ConsumptionDetail
	13, // 6: currency.GetTransactionHistoryResponse.transactions:type_name -> currency.Transaction
	0,  // 7: currency.CurrencyService.GetBalance:input_type -> currency.GetBalanceRequest
	2,  // 8: currency.CurrencyService.Grant:input_type -> currency.GrantRequest
	4,  // 9: currency.CurrencyService.Consume:input_type -> currency.ConsumeRequest
	7,  // 10: currency.CurrencyService.ProcessPayment:input_type -> currency.ProcessPaymentRequest
	9,  // 11: currency.CurrencyService.RedeemCode:input_type -> currency.RedeemCodeRequest
	11, // 12: currency.CurrencyService.GetTransactionHistory:input_type -> currency.GetTransactionHistoryRequest
	1,  // 13: currency.CurrencyService.GetBalance:output_type -> currency.GetBalanceResponse
	3,  // 14: currency.CurrencyService.Grant:output_type -> currency.GrantResponse
	5,  // 15: currency.CurrencyService.Consume:output_type -> currency.ConsumeResponse
	8,  // 16: currency.CurrencyService.ProcessPayment:output_type -> currency.ProcessPaymentResponse
	10, // 17: currency.CurrencyService.RedeemCode:output_type -> currency.RedeemCodeResponse
	12, // 18: currency.CurrencyService.GetTransactionHistory:output_type -> currency.GetTransactionHistoryResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_currency_proto_init() }
func file_currency_proto_init() {
	if File_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_currency_proto_rawDesc), len(file_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_proto_goTypes,
		DependencyIndexes: file_currency_proto_depIdxs,
		MessageInfos:      file_currency_proto_msgTypes,
	}.Build()
	File_currency_proto = out.File
	file_currency_proto_goTypes = nil
	file_currency_proto_depIdxs = nil
}
