// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/users/{user_id}/balance": {
            "get": {
                "description": "指定されたユーザーの通貨残高を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "残高を取得（管理API）",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user123",
                        "description": "ユーザーID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "APIキー",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "残高取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.BalanceResponse"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{user_id}/consume": {
            "post": {
                "description": "指定されたユーザーの通貨を消費します。優先順位制御も可能です",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "通貨を消費（管理API）",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user123",
                        "description": "ユーザーID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "APIキー",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "通貨消費リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ConsumeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通貨消費成功",
                        "schema": {
                            "$ref": "#/definitions/handler.ConsumeResponse"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "残高不足",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{user_id}/grant": {
            "post": {
                "description": "指定されたユーザーに無償通貨を付与します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "通貨を付与（管理API）",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user123",
                        "description": "ユーザーID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "APIキー",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "通貨付与リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.GrantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通貨付与成功",
                        "schema": {
                            "$ref": "#/definitions/handler.GrantResponse"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{user_id}/issue_token": {
            "post": {
                "description": "ユーザーIDを元にJWT認証トークンを生成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "認証トークンを生成",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ユーザーID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "トークン生成成功",
                        "schema": {
                            "$ref": "#/definitions/handler.GenerateTokenResponse"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{user_id}/transactions": {
            "get": {
                "description": "指定されたユーザーのトランザクション履歴を取得します。ページネーションとフィルタリングに対応しています",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "トランザクション履歴を取得（管理API）",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user123",
                        "description": "ユーザーID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "APIキー",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "example": 50,
                        "description": "取得件数（デフォルト: 50, 最大: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "example": 0,
                        "description": "オフセット（デフォルト: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "paid",
                        "description": "通貨タイプでフィルタ（paid/free）",
                        "name": "currency_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "consume",
                        "description": "トランザクションタイプでフィルタ（grant/consume/payment/redemption）",
                        "name": "transaction_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "履歴取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.TransactionHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/codes/redeem": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "引き換えコードを使用して通貨を付与します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "redemption"
                ],
                "summary": "コードを引き換え",
                "parameters": [
                    {
                        "description": "コード引き換えリクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RedeemCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "コード引き換え成功",
                        "schema": {
                            "$ref": "#/definitions/handler.RedeemCodeResponse"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "コードが見つからない",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/me/balance": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "自分の通貨残高を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currency"
                ],
                "summary": "残高を取得",
                "responses": {
                    "200": {
                        "description": "残高取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.BalanceResponse"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/me/transactions": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "自分のトランザクション履歴を取得します。ページネーションとフィルタリングに対応しています",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "トランザクション履歴を取得",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "example": 50,
                        "description": "取得件数（デフォルト: 50, 最大: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "example": 0,
                        "description": "オフセット（デフォルト: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "paid",
                        "description": "通貨タイプでフィルタ（paid/free）",
                        "name": "currency_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "consume",
                        "description": "トランザクションタイプでフィルタ（grant/consume/payment/redemption）",
                        "name": "transaction_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "履歴取得成功",
                        "schema": {
                            "$ref": "#/definitions/handler.TransactionHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payment/process": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "決済リクエストを処理し、通貨を消費します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "決済を処理",
                "parameters": [
                    {
                        "description": "決済処理リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ProcessPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "決済処理成功",
                        "schema": {
                            "$ref": "#/definitions/handler.ProcessPaymentResponse"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "残高不足",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.BalanceItem": {
            "description": "残高アイテム",
            "type": "object",
            "properties": {
                "free": {
                    "type": "string",
                    "example": "500"
                },
                "paid": {
                    "type": "string",
                    "example": "1000"
                }
            }
        },
        "handler.BalanceResponse": {
            "description": "残高レスポンス",
            "type": "object",
            "properties": {
                "balances": {
                    "$ref": "#/definitions/handler.BalanceItem"
                },
                "user_id": {
                    "type": "string",
                    "example": "user123"
                }
            }
        },
        "handler.ConsumeRequest": {
            "description": "通貨消費リクエスト",
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "50"
                },
                "currency_type": {
                    "type": "string",
                    "enum": [
                        "paid",
                        "free",
                        "auto"
                    ],
                    "example": "paid"
                },
                "item_id": {
                    "type": "string",
                    "example": "item001"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "use_priority": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "handler.ConsumeResponse": {
            "description": "通貨消費レスポンス",
            "type": "object",
            "properties": {
                "balance_after": {
                    "type": "string",
                    "example": "950"
                },
                "consumption_details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ConsumptionDetail"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                },
                "total_consumed": {
                    "type": "string",
                    "example": "50"
                },
                "transaction_id": {
                    "type": "string",
                    "example": "txn_456"
                }
            }
        },
        "handler.ConsumptionDetail": {
            "description": "消費詳細",
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "50"
                },
                "balance_after": {
                    "type": "string",
                    "example": "950"
                },
                "balance_before": {
                    "type": "string",
                    "example": "1000"
                },
                "currency_type": {
                    "type": "string",
                    "example": "paid"
                }
            }
        },
        "handler.ErrorResponse": {
            "description": "エラーレスポンス",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request body"
                }
            }
        },
        "handler.GenerateTokenResponse": {
            "description": "トークン生成レスポンス",
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer",
                    "example": 3600
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcjEyMyIsImV4cCI6MTcwMDAwMDAwMH0.signature"
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "handler.GrantRequest": {
            "description": "通貨付与リクエスト",
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "100"
                },
                "currency_type": {
                    "type": "string",
                    "enum": [
                        "paid",
                        "free"
                    ],
                    "example": "free"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "reason": {
                    "type": "string",
                    "example": "イベント報酬"
                }
            }
        },
        "handler.GrantResponse": {
            "description": "通貨付与レスポンス",
            "type": "object",
            "properties": {
                "balance_after": {
                    "type": "string",
                    "example": "600"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                },
                "transaction_id": {
                    "type": "string",
                    "example": "txn_123"
                }
            }
        },
        "handler.ProcessPaymentRequest": {
            "description": "決済処理リクエスト",
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "1000"
                },
                "currency": {
                    "type": "string",
                    "example": "JPY"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "method_name": {
                    "type": "string",
                    "example": "credit_card"
                },
                "payment_request_id": {
                    "type": "string",
                    "example": "req_123"
                }
            }
        },
        "handler.ProcessPaymentResponse": {
            "description": "決済処理レスポンス",
            "type": "object",
            "properties": {
                "consumption_details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ConsumptionDetail"
                    }
                },
                "payment_request_id": {
                    "type": "string",
                    "example": "req_123"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                },
                "total_consumed": {
                    "type": "string",
                    "example": "1000"
                },
                "transaction_id": {
                    "type": "string",
                    "example": "txn_789"
                }
            }
        },
        "handler.RedeemCodeRequest": {
            "description": "コード引き換えリクエスト",
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "REDEEM123"
                }
            }
        },
        "handler.RedeemCodeResponse": {
            "description": "コード引き換えレスポンス",
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "500"
                },
                "balance_after": {
                    "type": "string",
                    "example": "1000"
                },
                "code": {
                    "type": "string",
                    "example": "REDEEM123"
                },
                "currency_type": {
                    "type": "string",
                    "enum": [
                        "paid",
                        "free"
                    ],
                    "example": "free"
                },
                "redemption_id": {
                    "type": "string",
                    "example": "red_123"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                },
                "transaction_id": {
                    "type": "string",
                    "example": "txn_456"
                }
            }
        },
        "handler.TransactionHistoryResponse": {
            "description": "トランザクション履歴レスポンス",
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 50
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 1
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.TransactionItem"
                    }
                }
            }
        },
        "handler.TransactionItem": {
            "description": "トランザクションアイテム",
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "100"
                },
                "balance_after": {
                    "type": "string",
                    "example": "900"
                },
                "balance_before": {
                    "type": "string",
                    "example": "1000"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "currency_type": {
                    "type": "string",
                    "example": "paid"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                },
                "transaction_id": {
                    "type": "string",
                    "example": "txn_123"
                },
                "transaction_type": {
                    "type": "string",
                    "example": "consume"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "JWT認証トークン。形式: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Gem Server API",
	Description:      "仮想通貨管理サービスのREST API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
